### ISSUE TITLE
vysmaw application crash

### ISSUE THREAD

**Issue by caseyjlaw** [mpokorny/vysmaw#27]
I'm using vysmaw_reader (from the vysmaw_apps repo) to read spectra. Very rarely, I see a crash on the vysmaw side like this:
```
Reading /home/cbe-master/realfast/soft/vysmaw_apps/vys.conf
Expecting 2 ints, 351 bls, and 44928 total spectra between times 1502385523.0 and 1502385525.0 (timeout 2.0+10 s)
At spec 0: 0 % of data in 0.0x realtime
**
ERROR:/users/mpokorny/projects/vysmaw/src/spectrum_reader.c:1059:to_quit_state: assertion failed: (context->state != STATE_DONE)
```

All but the last line from from my vysmaw_reader cython application. The last line is the one relevant to this repo. It isn't an urgent issue, but raising it here to keep track of it.

**Comment by mpokorny** [comment]
I have a fix for this in commit 97582c5, but it has not been tested. I will rebuild the library on the cbe cluster tomorrow, after which you can give it a try.

**Comment by mpokorny** [comment]
I've installed this version on the cbe cluster. Still not tested...hopefully nothing was broken. You may not even have to rebuild your application on the cbe if it's dynamically linked with libvysmaw and libvys, which I suspect is the case.

**Comment by caseyjlaw** [comment]
Ok, my tests today do not see this error. Looks like this issue can be closed.
