### ISSUE TITLE
find way to for vysmaw apps to read without locking Python GIL

### ISSUE THREAD

**Issue by caseyjlaw** [mpokorny/vysmaw#34]
I have a vysmaw_reader application that catches data well. However, there the key line for reading a spectrum from a vysmaw message locks the Python GIL. The line is at:
https://github.com/realfastvla/vysmaw_apps/blob/development/vysmaw_reader.pyx#L274.

This can make the workers in the realfast cluster unreachable for tens of seconds. This in turn produces some instability to the job scheduler.
I have fumbled with the cython memoryviews and other memory management features quite a bit. I think someone with a bit more C experience may have better luck interpreting the types and issues with c/python interoperability.
The goal is to have a vysmaw app that can wrap line 274 (linked above) with a "nogil" context.

**Comment by mpokorny** [comment]
I'm not entirely sure that I see why that line locks the GIL. Might it be happening in the ValidBufferMessage.spectrum property (method) at https://github.com/mpokorny/vysmaw/blob/54cd25d1bd04851519cb35764618b07d33683003/py/cy_vysmaw.pyx#L542 I don't see why line 274 shouldn't just amount to a casting operation, but then again, I'm no expert on cython memoryviews. I would hope that there's no copying going on there, and if there's not, the GIL, if it is being locked, shouldn't be locked for long. I suppose that it might help you to get an array of complex numbers from the spectrum property, but then again the spectrum() method already does something very similar to what your application code is doing, so perhaps the locking occurs there too.  The spectrum() method implementation is _slightly_ different, however. In any case, seeing that your code is simply using the spectrum array as the source of values to copy to the data array, perhaps that could be done by referencing the underlying C array directly, which shouldn't need the GIL and should be the goal. Are you sure that copying the data from the spectrum array to the data array isn't where the locking is occurring?

**Comment by mpokorny** [comment]
My initial reading of the C code generated from cy_vysmaw.pyx is that the creation of the memoryview in ValidBufferMesssage.spectrum() does not copy the array. There might be other code in there that needs the GIL, but it's hard to see what else would take significant time to complete.
My suggestion (untested) is to remove https://github.com/realfastvla/vysmaw_apps/blob/337762e3ab6f2045d8c4a4bbe156d8b30bdee1f3/vysmaw_reader.pyx#L211, and to change L274 to
```python
cdef cnp.complex64_t[:] spectrum = <cnp.complex64_t[:self.nchan]>msg[0].content.valid_buffer.spectrum
```
Not sure that the cast on the right hand side above will work, or is necessary. I could certainly change the return value type of ValueBufferMessage.spectrum in case it's a problem.

**Comment by caseyjlaw** [comment]
Cython does not allow a cdef in a for loop.
If I define on L211 it as:
`cdef cnp.complex64_t[::1] spectrum`

and then assign the pointer to it on L 274 as you suggested, I get a cython error during compilation:
"Pointer base type does not match cython.array base type"

**Comment by mpokorny** [comment]
I'm going to try to return a complex type array from ValidBufferMessage.spectrum. Unfortunately, I'm not sure that's actually possible given the types C and Cython have available. I'll look into it.

**Comment by caseyjlaw** [comment]
I have tested this new complex type and it works as expected. Feel free to close this issue.

**Comment by mpokorny** [comment]
Glad that it worked.
