### ISSUE TITLE
change type of config spectrum_buffer_pool_size 

### ISSUE THREAD

**Issue by caseyjlaw** [mpokorny/vysmaw#35]
I'm working on very large vysmaw reads (few to several GB). My current design sets the buffer pool size (config.spectrum_buffer_pool_size) to be the total expected size of all spectra. vysmaw defines this parameter as an unsigned int, so it is too small to hold values larger than 4 GB.

**Comment by mpokorny** [comment]
In vysmaw.h, as well as vysmaw.pxd, spectrum_buffer_pool_size has type size_t, and the parsing code reads it from the configuration file as a 64 bit integer, so the issue doesn't lie in the C code. However, in vy_vysmaw.pyx, the Configuration.spectrum_buffer_pool_size setter method takes only an unsigned int value -- I'll try changing that to size_t, and then you should test it.

**Comment by caseyjlaw** [comment]
Ok, that seems likely to work.

**Comment by mpokorny** [comment]
I've made this change, as well as the change in the type of the value returned from ValidBufferMessage.spectrum (potentially useful for issue #34), both of which will go into vysmaw 2.0.0. The libvysmaw/libvys major version change, the python 3.6 installation changes, and some (realfast-related) changes to wcbe have converged, and we're doing some testing now on the whole lot to see that there are no major flaws. The code changes themselves amount to very little. I'll update you when things have settled, and then you should try the newest version of vysmaw.

**Comment by caseyjlaw** [comment]
Has there been a chance to test vysmaw 2.0.0?
I noticed an update to vyssim syntax. Is that is part of the same update?

**Comment by mpokorny** [comment]
Yes, that's part of the update. vysmaw 2.0.0 has been installed on the CBE, and you should be able to try it, as a ~~guinea pig~~ tester. There were no changes to the vys protocol with vysmaw 2.0.0, so vysmaw 2.0.0 should work with any recent version of wcbe.

**Comment by caseyjlaw** [comment]
I'm testing now. Were there any changes that might affect how the filter functions should work?
I have a time filter function like this
```
@cython.boundscheck(False)
@cython.wraparound(False)
cdef void filter_time(const char *config_id, const uint8_t *stns, uint8_t bb_idx, uint8_t bb_id, uint8_t spw,
             uint8_t pol, const vys_spectrum_info *infos, uint8_t num_infos,
             void *user_data, bool *pass_filter) nogil:

    cdef cnp.float64_t *select = <cnp.float64_t *>user_data
    cdef unsigned int i

    cdef cnp.float64_t t0 = select[0]
    cdef cnp.float64_t t1 = select[1]
#    cdef long t0
#    cdef long t1
#    t0 = <long> select[0]*1000
#    t1 = <long> select[1]*1000

    for i in range(num_infos):
        ts = infos[i].timestamp * 1./1000000000
        if t0 <= ts and ts < t1:
            pass_filter[i] = True
        else:
            pass_filter[i] = False

    return
```

It used to pass data in a time window t0 to t1. Now it passes nothing (only NULL type, after a message pop timeout). I've confirmed that if I replace the filter logic with a `pass_filter[i] = True`, then messages come through.
I'm guessing the timestamp or my t0/t1 types are not right, but I didn't think that was part of this change.
Any ideas?

**Comment by mpokorny** [comment]
That surprises me, as nothing about the signal messages or the callback has changed. Are you able to inspect the `info` parameter values from your callback in any way? Even by printing a few, maybe? It might be interesting to see a few of the infos `timestamp` values. I'm hope that this isn't an obscure consequence of the python 3.6 change. Have you checked that your cython code is linking with the correct vysmaw library?

**Comment by caseyjlaw** [comment]
I ran a test by removing the lower bound on the time filter and caught messages from vyssim.
Then I caught messages from the standard port (224.0.0.100) and confirmed that the timestamp is about right in live observations. The same test with messages from vyssim had timestamps that were about 500s *in the past*.
I will keep poking at it, but it may be that the time stamps from the new version of vyssim are not quite right.

**Comment by caseyjlaw** [comment]
A little more playing suggests that the time of the messages are generally similar to the start time of the vyssim command execution. In the past, I could let run vyssim and the timestamp of a message received at any given time would be similar to the present time.

**Comment by mpokorny** [comment]
I think this issue is solved. To follow up on the vyssim issue, I've create issue #38.
