### ISSUE TITLE
memory error

### ISSUE THREAD

**Issue by caseyjlaw** [mpokorny/vysmaw#40]
I have vysmaw 2 largely working (using vyssim). I have seen some sporadic crashes, though. I'll report it for now, in case it triggers any ideas for you:

The context is that I am reading with vysmaw_reader.pyx (see my vysmaw_apps repo). It starts up fine and enters a loop to pull messages from the queue. After pulling a (at least one) message, it crashes with this error:
```
***MEMORY-ERROR***: [5315]: GSlice: assertion failed: sinfo->n_allocated > 0
```

I don't have much more, but will elaborate if I can reproduce it reliably.

**Comment by mpokorny** [comment]
Oy, that's an error in one of the libraries that vysmaw uses. Once you can reproduce it reliably, try running your app with the environment variable setting G_SLICE=always-malloc, and see whether that makes a difference. I guess it might be possible that the library's memory management routines are clashing with Python/Cython somehow; only a guess. In any case, do try setting the environment variable.

**Comment by caseyjlaw** [comment]
I saw the error again this morning. It appear sporadically, but I see one or two crashes if I run the client a few dozen times in a row.
If I set that environment variable, I see no such error. I'll leave that in for now.

**Comment by caseyjlaw** [comment]
Oops. I take that back. I saw another error instance of the error this morning:
```
***MEMORY-ERROR***: [29156]: GSlice: assertion failed: sinfo->n_allocated > 0
```

I am setting the `G_SLICE=always-malloc` in the environment that runs the client. I am usually running tests in which I submit dozens of jobs to a cluster of ~10 GPUs (not all are up atm). My job scheduler shows that the error will kill one of the workers after a few reads, but eventually all workers are killed and restarted.

**Comment by caseyjlaw** [comment]
I take back the slanderous things I said about the G_SLICE environment variable. I have things working again.

**Comment by mpokorny** [comment]
If you have the time, try running with G_SLICE=debug-blocks and see what happens. If your application still crashes, which I expect it would, I would be interested in the output that is reported. Afterwards I might be interested in trying to run your application in a debugger to see where the problem could be in the vysmaw code. No rush on that, except of course if the current G_SLICE workaround proves faulty.

**Comment by caseyjlaw** [comment]
Indeed that env does report something. New error message:
```
GSlice: MemChecker: attempt to release block with invalid size: 0x7fc75c0099d0 size=15976 invalid-size=3016
```

The value of `invalid-size` varies between crashes . I also see values of 232, 808, 2248, 3208.
Need any more info on that?

**Comment by mpokorny** [comment]
I just fixed this in my development version. I was able to reproduce the error, and based on that test, the issue is solved. When I get around to creating an official new version, that fix should appear. I'll close this issue after the fix appears in this repository.

**Comment by caseyjlaw** [comment]
So the result is will be that I no longer need to set `G_SLICE=always-malloc`? Or do you anticipate other benefits?

**Comment by mpokorny** [comment]
The bug certainly caused some level of memory corruption whenever you ran without setting `G_SLICE=always-malloc`, so the benefits include the avoidance of the effects of that memory corruption (which are unpredictable). Not using the `G_SLICE` setting means _vysmaw_ uses a more performant memory management system.

**Comment by caseyjlaw** [comment]
Ok, thanks. I've removed the environment variable from my set up for realfast code. Let me know if you think a test would be useful.
